# Generated by Django 5.0.4 on 2024-05-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='std',
        ),
        migrations.CreateModel(
            name='assigned_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('wrk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.work')),
            ],
        ),
    ]
